# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{iphone_mvc}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["felix8g"]
  s.date = %q{2010-05-09}
  s.default_executable = %q{mvc-gen}
  s.description = %q{generate a puremvc framework skeleton files for writing iphone app}
  s.email = %q{felix8g@gmail.com}
  s.executables = ["mvc-gen"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/mvc-gen",
     "iphone_mvc.gemspec",
     "lib/iphone_mvc.rb",
     "lib/iphone_mvc/generators/ApplicationFacade.h.tt",
     "lib/iphone_mvc/generators/ApplicationFacade.m.tt",
     "lib/iphone_mvc/generators/app.rb",
     "lib/iphone_mvc/generators/controllers/.gitignore",
     "lib/iphone_mvc/generators/models/.gitignore",
     "lib/iphone_mvc/generators/models/enum/.gitignore",
     "lib/iphone_mvc/generators/models/vo/.gitignore",
     "lib/iphone_mvc/generators/utils/.gitignore",
     "lib/iphone_mvc/generators/utils/NSStringWhiteSpace.h",
     "lib/iphone_mvc/generators/utils/NSStringWhiteSpace.m",
     "lib/iphone_mvc/generators/utils/UIDevice.h",
     "lib/iphone_mvc/generators/utils/UIDevice.m",
     "lib/iphone_mvc/generators/utils/URLEncodeString.h",
     "lib/iphone_mvc/generators/utils/URLEncodeString.m",
     "lib/iphone_mvc/generators/views/.gitignore",
     "lib/iphone_mvc/generators/views/components/.gitignore",
     "spec/iphone_mvc_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/felix8g/iphone_mvc}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{puremvc iphone application generator}
  s.test_files = [
    "spec/iphone_mvc_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<mocha>, [">= 0.9.7"])
      s.add_development_dependency(%q<rack-test>, [">= 0.5.0"])
      s.add_development_dependency(%q<webrat>, [">= 0.5.1"])
      s.add_development_dependency(%q<fakeweb>, [">= 1.2.3"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<mocha>, [">= 0.9.7"])
      s.add_dependency(%q<rack-test>, [">= 0.5.0"])
      s.add_dependency(%q<webrat>, [">= 0.5.1"])
      s.add_dependency(%q<fakeweb>, [">= 1.2.3"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<mocha>, [">= 0.9.7"])
    s.add_dependency(%q<rack-test>, [">= 0.5.0"])
    s.add_dependency(%q<webrat>, [">= 0.5.1"])
    s.add_dependency(%q<fakeweb>, [">= 1.2.3"])
  end
end

